services:
  vote: #service name
    scale: 3 #create 3 of these
    image: dockersamples/examplevotingapp_vote 
    ports:
      - "5000-5005:80" #format host_port:container_port. Remember that we will create 3 containers
    networks: #which networks will this container belong to?
      - front-tier
      - back-tier

  result:
    image: dockersamples/examplevotingapp_result
    ports:
      - "5001:80"
    networks:
      - front-tier
      - back-tier

  worker:
    image: dockersamples/examplevotingapp_worker
    networks:
      - back-tier

  redis:
    image: redis:alpine
    volumes:
      - "./healthchecks:/healthchecks"
    networks:
      - back-tier

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - "db-data:/var/lib/postgresql/data"
      - "./healthchecks:/healthchecks"
    networks:
      - back-tier

volumes:
  db-data: #define external volume for the databases

networks:
  front-tier:
  back-tier: